version: "3.8"
services:
  mongo-DB:
    container_name: mongo-DB
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
  mongo-Express:
    container_name: mongo-Express
    image: mongo-express
    depends_on:
      - mongo-DB
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-DB
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - '8081:8081'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client-app
    ports:
      - '8080:80'  